### ISSUE TITLE
Notes are not updated in Roam if they are edited in Matter

### ISSUE THREAD

**Issue by benwoodward** [getmatterapp/roam-matter#13]
In Matter for web, you can hit 'N' to create a new note, or make a selection then hit 'N' to make a highlight with a note. In both situations, the note or highlight plus note are synced to Roam, however, if you edit either of these note types, the changes are not reflected in Roam.

**Comment by hunterclarke** [comment]
Hey Ben, this is by design at the moment. A lot of folks update the highlights/notes once they arrive in Roam. We want to avoid overriding any of those changes after the fact. 

It also gets quite complex trying to match up a highlight on the Matter side with a highlight on the Roam side. We don't have an identifier that syncs one to the other.

Thanks for the suggestion! At this point deleting/recreating the highlight & note will sync over the updated content.

**Comment by benwoodward** [comment]
Makes sense. In that case, it'd be great if I could make multiple page notes, i.e. the note that is attached to the page rather than a highlight, and for each of those page notes to be synced into Roam.
